# Site settings
title: madranger | blog
SEOTitle: madranger | blog
header-img: img/home-bg.jpg
email: lichence@gmail.com
description: "Every failure is leading towards success."
keyword: "madranger, pmp, pmp-acp, agile, python, .net, kayak"
url: "http://madranger.com"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/imadranger/madranger.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "True mastery of any skill takes a lifetime"
sidebar-avatar: /img/avatar_me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     username
# zhihu_username:     username
github_username:    imadranger
facebook_username:  lichence
instagram_username: hikingjack
#jianshu_username:   e71990ada2fd
#twitter_username:   username




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
#disqus_username: imadranger

# Gitalk
gitalk:
 enable: true    #是否开启Gitalk评论
 clientID: 0a0f3d5cb9e4eaa1fad6                            #生成的clientID
 clientSecret: 165c46eee15e713bfdf777c442fc35b28901e242    #生成的clientSecret
 repo: imadranger.github.io    #仓库名称
 owner: imadranger    #github用户名
 admin: imadranger
 distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-138659050-1'            # Format: UA-xxxxxx-xx
ga_domain: madranger.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "cro",
        href: "http://blog.icro.me/"
    }
   #,{
   #       title: "简书·BY",
   #      href: "http://www.jianshu.com/u/e71990ada2fd"
   # },{
   #     title: "Apple",
   #     href: "https://apple.com"
   # },{
   #     title: "Apple Developer",
   #     href: "https://developer.apple.com/"
   # }
]
